services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ConnectionStrings__Database: "Host=db;Port=5432;Database=dev;Username=${DB_USER};Password=${DB_PASSWORD}"
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  web:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - server
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data: {}
